# Generated by Django 4.2.4 on 2023-10-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20231021_2226'),
    ]

    operations = [
    ]
